<?php

function pet_menu() {
    $pet = [];
    $pet['favorite_pet'] = [
        'title' => 'Twinkles, the Hedgehog',
        'page callback' => 'pet_info',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    ];

    return $pet;
}

function pet_info() {
    return '<h1>There once was a hedgehog named Twinkles...</h1>
            <p>Collaboratively administrate empowered markets
            via plug-and-play networks. Dynamically procrastinate B2C users
            after installed base benefits. Dramatically visualize customer
            directed convergence without revolutionary ROI.</p>

            <p>Efficiently unleash cross-media information without
            cross-media value. Quickly maximize timely deliverables for
            real-time schemas. Dramatically maintain clicks-and-mortar
            solutions without functional solutions.</p>

            <p>Completely synergize resource sucking relationships via premier
            niche markets. Professionally cultivate one-to-one customer
            service with robust ideas. Dynamically innovate resource-leveling
            customer service for state of the art customer service.</p>
        ';
}
